# Пути к моделям
CLASSIFIER_MODEL_PATH = "models/classifier_cnn.pth"

# Пути к данным
DATASET_PATH = "dataset/"
OUTPUT_XML_PATH = "output/result.musicxml"

# Параметры изображений
SYMBOL_IMAGE_SIZE = (64, 64)
STAFF_PADDING = 10

# Флаги
DEBUG = True
SAVE_INTERMEDIATE_IMAGES = False

# Экспорт
MUSICXML_AUTHOR = "AutoGenerated"
MUSICXML_TITLE = "Untitled"

# Прочее
MIN_SYMBOL_CONFIDENCE = 0.7